import { PageHeader } from "@/components/PageHeader";
import { StatePanel } from "@/components/StatePanel";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { useOrganization } from "@/contexts/OrganizationContext";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, Fingerprint, UserRound } from "lucide-react";
import { useState } from "react";

export default function AuditLogPage() {
  const { activeOrganizationId, hasPermission } = useOrganization(); const [entityType, setEntityType] = useState("all");
  const query = trpc.organizations.audit.useQuery({ organizationId: activeOrganizationId || 0, entityType: entityType === "all" ? undefined : entityType, limit: 100 }, { enabled: Boolean(activeOrganizationId && hasPermission("audit:view")) });
  return <div className="space-y-7"><PageHeader eyebrow="Append-only trace" title="Audit Log" description="Track who changed what, when, and how — within the organization boundary." actions={hasPermission("audit:view") ? <Select value={entityType} onValueChange={setEntityType}><SelectTrigger className="w-44 bg-card"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All entities</SelectItem><SelectItem value="case">Cases</SelectItem><SelectItem value="variant">Variants</SelectItem><SelectItem value="interpretation">Interpretations</SelectItem><SelectItem value="report">Reports</SelectItem><SelectItem value="organization_member">Members</SelectItem></SelectContent></Select> : undefined} />
    {!hasPermission("audit:view") ? <StatePanel type="forbidden" title="You do not have permission to view the audit log" description="Ask your organization administrator for a role that includes the audit:view action. Organization events outside your permissions remain hidden." /> : query.isError ? <StatePanel type="error" title="Failed to load audit log" description={query.error.message} onRetry={() => { void query.refetch(); }} /> : query.isLoading ? <div className="space-y-3">{Array.from({ length: 7 }).map((_, index) => <Skeleton key={index} className="h-24" />)}</div> : query.data?.length ? <div className="relative space-y-3 before:absolute before:bottom-8 before:left-[30px] before:top-8 before:w-px before:bg-border">{query.data.map(event => <article key={event.id} className="clinical-card relative grid gap-4 p-5 sm:grid-cols-[40px_1fr_auto]"><div className="relative z-10 grid size-10 place-items-center rounded-xl border border-border bg-card text-primary"><Activity className="size-4" /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-semibold">{event.action}</p><span className="status-pill bg-muted text-muted-foreground">{event.entityType} #{event.entityId || "—"}</span></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[10px] text-muted-foreground"><UserRound className="size-3" /><span>Actor #{event.actorUserId || "system"}</span><Fingerprint className="ml-2 size-3" /><span className="font-mono">{event.requestId || "no request id"}</span></div>{event.before || event.after ? <div className="mt-4 grid items-start gap-2 text-[9px] sm:grid-cols-[1fr_auto_1fr]"><pre className="overflow-auto rounded-lg bg-rose-50 p-3 text-rose-800">{JSON.stringify(event.before, null, 2) || "—"}</pre><ArrowRight className="mt-3 hidden size-3 text-muted-foreground sm:block" /><pre className="overflow-auto rounded-lg bg-emerald-50 p-3 text-emerald-800">{JSON.stringify(event.after, null, 2) || "—"}</pre></div> : null}</div><time className="text-[10px] text-muted-foreground">{new Date(event.createdAt).toLocaleString()}</time></article>)}</div> : <StatePanel type="empty" title="No audit events to display" description="When clinical data or administrative actions occur within the organization, request metadata and before/after records will appear here." />}
  </div>;
}
