import { ClinicalStatus } from "@/components/ClinicalStatus";
import { PageHeader } from "@/components/PageHeader";
import { StatePanel } from "@/components/StatePanel";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useOrganization } from "@/contexts/OrganizationContext";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, ArrowRight, CheckCircle2, Clock3, Database, Dna, FileArchive, FlaskConical } from "lucide-react";
import { useLocation, useParams } from "wouter";
import { toast } from "sonner";

export default function CaseDetailPage() {
  const params = useParams<{ id: string }>(); const caseId = Number(params.id); const { activeOrganizationId, hasPermission } = useOrganization(); const [, navigate] = useLocation();
  const query = trpc.cases.get.useQuery({ organizationId: activeOrganizationId || 0, caseId }, { enabled: Boolean(activeOrganizationId && caseId && hasPermission("case:read")) }); const timeline = trpc.cases.timeline.useQuery({ organizationId: activeOrganizationId || 0, caseId }, { enabled: Boolean(activeOrganizationId && caseId && hasPermission("case:read")) });
  const createReport = trpc.reports.createDraft.useMutation({ onSuccess: result => navigate(`/reports/${result.id}`), onError: error => toast.error(error.message) });
  if (!hasPermission("case:read")) return <div className="space-y-7"><PageHeader eyebrow="Case management" title="케이스" description="조직 범위의 임상 케이스를 조회합니다." /><StatePanel type="forbidden" title="케이스 조회 권한이 없습니다" description="조직 관리자에게 case:read 액션이 포함된 역할을 요청하십시오." action={<Button variant="outline" onClick={() => navigate("/")}>대시보드</Button>} /></div>;
  if (query.isLoading) return <div className="space-y-5"><Skeleton className="h-24" /><Skeleton className="h-80" /></div>;
  if (query.isError) return <div className="space-y-7"><PageHeader eyebrow="Case management" title="케이스 조회 오류" description="요청한 케이스와 조직 접근 경계를 확인할 수 없습니다." /><StatePanel type="error" title="케이스를 불러오지 못했습니다" description={query.error.message} onRetry={() => { void query.refetch(); }} action={<Button variant="outline" onClick={() => navigate("/cases")}><ArrowLeft className="mr-2 size-4" />목록</Button>} /></div>;
  if (!query.data) return <div className="space-y-7"><PageHeader eyebrow="Case management" title="케이스 없음" description="요청한 케이스 식별자를 확인하십시오." /><StatePanel type="empty" title="케이스를 찾을 수 없습니다" description="삭제되었거나 현재 조직에 속하지 않은 케이스는 노출되지 않습니다." action={<Button variant="outline" onClick={() => navigate("/cases")}><ArrowLeft className="mr-2 size-4" />목록</Button>} /></div>;
  const item = query.data;
  return <div className="space-y-7"><PageHeader eyebrow={`${item.purpose} · ${item.inputType}`} title={item.caseNumber} description={`${item.patientAlias} · ${item.referenceBuild} · ${item.panelName || "패널 미지정"}`} badge={item.status} actions={<><Button variant="outline" onClick={() => navigate("/cases")}><ArrowLeft className="mr-2 size-4" />목록</Button>{item.variantCount > 0 ? <>{hasPermission("report:draft") ? <Button variant="outline" onClick={() => createReport.mutate({ organizationId: activeOrganizationId!, caseId: item.id })} disabled={createReport.isPending}>보고서 초안</Button> : null}<Button onClick={() => navigate(`/workbench/${item.id}`)}><FlaskConical className="mr-2 size-4" />변이 {item.variantCount.toLocaleString()}개</Button></> : null}</>} />
    {createReport.error ? <StatePanel compact type="error" title="보고서 초안을 생성하지 못했습니다" description={createReport.error.message} onRetry={() => createReport.mutate({ organizationId: activeOrganizationId!, caseId: item.id })} /> : null}
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([{ label: "분석 상태", value: <ClinicalStatus status={item.status} />, icon: Dna }, { label: "변이", value: item.variantCount.toLocaleString(), icon: Database }, { label: "샘플", value: item.samples.length, icon: FlaskConical }, { label: "파일", value: item.files.length, icon: FileArchive }]).map(({ label, value, icon: Icon }) => <Card key={label} className="clinical-card shadow-none"><CardContent className="flex items-center justify-between p-5"><div><p className="text-xs text-muted-foreground">{label}</p><div className="mt-2 text-lg font-semibold">{value}</div></div><Icon className="size-5 text-primary" /></CardContent></Card>)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">분석 타임라인</CardTitle></CardHeader><CardContent className="space-y-0">{timeline.isError ? <StatePanel compact type="error" title="타임라인을 불러오지 못했습니다" description={timeline.error.message} onRetry={() => { void timeline.refetch(); }} /> : timeline.data?.length ? timeline.data.map((event, index) => <div key={event.id} className="grid grid-cols-[28px_1fr] gap-3"><div className="flex flex-col items-center"><div className={`grid size-7 place-items-center rounded-full ${index === 0 ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{index === 0 ? <CheckCircle2 className="size-3.5" /> : <Clock3 className="size-3.5" />}</div>{index < timeline.data.length - 1 ? <div className="h-full w-px bg-border" /> : null}</div><div className="pb-6"><div className="flex flex-wrap items-center gap-2"><ClinicalStatus status={event.status} /><span className="font-mono text-[10px] text-muted-foreground">{event.progressPercent}%</span></div><p className="mt-2 text-sm leading-6">{event.message}</p><p className="mt-1 text-[10px] text-muted-foreground">{new Date(event.createdAt).toLocaleString()}</p></div></div>) : <StatePanel compact type="empty" title="타임라인이 없습니다" description="분석이 시작되면 상태 변경 이력이 이 영역에 표시됩니다." />}</CardContent></Card>
      <div className="space-y-5"><Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">샘플</CardTitle></CardHeader><CardContent className="space-y-3">{item.samples.map(sample => <div key={sample.id} className="flex items-center justify-between rounded-xl border border-border/70 px-4 py-3"><div><p className="font-mono text-xs font-medium">{sample.sampleCode}</p><p className="mt-1 text-[10px] text-muted-foreground">{sample.specimenType}</p></div><span className="text-xs capitalize text-muted-foreground">{sample.role}</span></div>)}</CardContent></Card><Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">입력 파일</CardTitle></CardHeader><CardContent className="space-y-3">{item.files.map(file => <div key={file.id} className="rounded-xl border border-border/70 px-4 py-3"><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-medium">{file.fileName}</p><span className="font-mono text-[9px] uppercase text-muted-foreground">{file.kind}</span></div><p className="mt-2 truncate font-mono text-[9px] text-muted-foreground">SHA-256 {file.sha256}</p></div>)}</CardContent></Card></div>
    </section>
  </div>;
}
