import { PageHeader } from "@/components/PageHeader";
import { StatePanel } from "@/components/StatePanel";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { useOrganization } from "@/contexts/OrganizationContext";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, Dna, FileUp, Info, Loader2, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type FormState = { projectId: string; caseNumber: string; patientAlias: string; purpose: "germline" | "somatic"; inputType: "vcf" | "fastq"; referenceBuild: "GRCh37" | "GRCh38"; panelName: string; indication: string; phenotypeText: string; sampleCode: string; specimenType: string; tumorContentPercent: string; consentClinicalAnalysis: boolean; consentSecondaryFindings: boolean; consentDataUse: boolean; };

async function sha256(file: File) { const digest = await crypto.subtle.digest("SHA-256", await file.arrayBuffer()); return Array.from(new Uint8Array(digest)).map(value => value.toString(16).padStart(2, "0")).join(""); }

export default function NewCasePage() {
  const { activeOrganizationId, hasPermission } = useOrganization();
  const [, navigate] = useLocation();
  const projects = trpc.projects.list.useQuery({ organizationId: activeOrganizationId || 0 }, { enabled: Boolean(activeOrganizationId) });
  const [form, setForm] = useState<FormState>({ projectId: "", caseNumber: `GVI-${new Date().getFullYear()}-`, patientAlias: "", purpose: "germline", inputType: "vcf", referenceBuild: "GRCh38", panelName: "", indication: "", phenotypeText: "", sampleCode: "", specimenType: "Blood", tumorContentPercent: "", consentClinicalAnalysis: false, consentSecondaryFindings: false, consentDataUse: false });
  const [vcf, setVcf] = useState<File | null>(null); const [r1, setR1] = useState<File | null>(null); const [r2, setR2] = useState<File | null>(null); const [progress, setProgress] = useState(0); const [submissionError, setSubmissionError] = useState("");
  const createCase = trpc.cases.create.useMutation(); const requestUpload = trpc.cases.requestUpload.useMutation(); const completeUpload = trpc.cases.completeUpload.useMutation(); const submit = trpc.cases.submit.useMutation();
  const busy = createCase.isPending || requestUpload.isPending || completeUpload.isPending || submit.isPending;
  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm(current => ({ ...current, [key]: value }));
  const upload = async (caseId: number, file: File, kind: "vcf" | "fastq_r1" | "fastq_r2") => { const ticket = await requestUpload.mutateAsync({ organizationId: activeOrganizationId!, caseId, kind, fileName: file.name }); const digest = await sha256(file); const response = await fetch(ticket.uploadUrl, { method: "PUT", headers: { "Content-Type": file.type || "application/octet-stream" }, body: file }); if (!response.ok) throw new Error(`${file.name} 업로드 실패`); await completeUpload.mutateAsync({ organizationId: activeOrganizationId!, caseId, kind, fileName: file.name, storageKey: ticket.key, accessUrl: ticket.accessUrl, mimeType: file.type || "application/octet-stream", byteSize: file.size, sha256: digest }); };
  const handleSubmit = async () => { if (!activeOrganizationId || !form.projectId || !form.consentClinicalAnalysis) return; try { setSubmissionError(""); setProgress(8); const created = await createCase.mutateAsync({ organizationId: activeOrganizationId, projectId: Number(form.projectId), caseNumber: form.caseNumber, patientAlias: form.patientAlias, purpose: form.purpose, inputType: form.inputType, referenceBuild: form.referenceBuild, panelName: form.panelName || undefined, indication: form.indication || undefined, phenotypeText: form.phenotypeText || undefined, consentClinicalAnalysis: true, consentSecondaryFindings: form.consentSecondaryFindings, consentDataUse: form.consentDataUse, samples: [{ sampleCode: form.sampleCode, role: form.purpose === "somatic" ? "tumor" : "proband", specimenType: form.specimenType, tumorContentPercent: form.purpose === "somatic" && form.tumorContentPercent ? Number(form.tumorContentPercent) : undefined }] }); setProgress(25); if (form.inputType === "vcf" && vcf) await upload(created.id, vcf, "vcf"); if (form.inputType === "fastq" && r1 && r2) { await upload(created.id, r1, "fastq_r1"); setProgress(58); await upload(created.id, r2, "fastq_r2"); } setProgress(82); await submit.mutateAsync({ organizationId: activeOrganizationId, caseId: created.id }); setProgress(100); toast.success("분석 의뢰가 접수되었습니다."); navigate(`/cases/${created.id}`); } catch (error) { const message = error instanceof Error ? error.message : "분석 의뢰 중 오류가 발생했습니다."; setSubmissionError(message); setProgress(0); toast.error(message); } };
  const fileReady = form.inputType === "vcf" ? Boolean(vcf) : Boolean(r1 && r2); const valid = Boolean(form.projectId && form.caseNumber.length >= 2 && form.patientAlias && form.sampleCode && fileReady && form.consentClinicalAnalysis);
  if (!hasPermission("case:create")) return <div className="space-y-7"><PageHeader eyebrow="New analysis request" title="분석 의뢰" description="검사 목적과 동의 범위를 구조화해 새 케이스를 접수합니다." /><StatePanel type="forbidden" title="케이스 생성 권한이 없습니다" description="조직 관리자에게 case:create 액션이 포함된 역할을 요청하십시오." action={<Button variant="outline" onClick={() => navigate("/cases")}><ArrowLeft className="mr-2 size-4" />케이스 목록</Button>} /></div>;
  if (projects.isError) return <div className="space-y-7"><PageHeader eyebrow="New analysis request" title="분석 의뢰" description="조직 프로젝트 범위를 확인하지 못했습니다." /><StatePanel type="error" title="프로젝트를 불러오지 못했습니다" description={projects.error.message} onRetry={() => { void projects.refetch(); }} action={<Button variant="outline" onClick={() => navigate("/cases")}><ArrowLeft className="mr-2 size-4" />케이스 목록</Button>} /></div>;
  return <div className="mx-auto max-w-5xl space-y-7"><PageHeader eyebrow="New analysis request" title="분석 의뢰" description="검사 목적과 동의 범위를 구조화하고 원본 파일을 조직·케이스 전용 저장 경로로 직접 업로드합니다." actions={<Button variant="ghost" onClick={() => navigate("/cases")}><ArrowLeft className="mr-2 size-4" />케이스로</Button>} />
    <Alert className="border-teal-200 bg-teal-50/60 text-teal-950"><ShieldCheck className="size-4 text-teal-700" /><AlertTitle>조직 격리 업로드</AlertTitle><AlertDescription className="text-teal-800/80">파일은 웹 서버를 경유하지 않고 현재 조직과 생성된 케이스 전용 S3 경로로 업로드되며 SHA-256 체크섬이 기록됩니다.</AlertDescription></Alert>
    {!projects.isLoading && !projects.data?.length ? <StatePanel compact type="empty" title="먼저 프로젝트를 생성하십시오" description="케이스는 조직 내부 프로젝트 경계에 속해야 합니다. 대시보드에서 프로젝트를 만든 뒤 다시 접수하십시오." action={<Button variant="outline" onClick={() => navigate("/")}>대시보드로 이동</Button>} /> : null}
    {submissionError ? <StatePanel compact type="error" title="분석 의뢰를 완료하지 못했습니다" description={submissionError} onRetry={() => { void handleSubmit(); }} /> : null}
    <div className="grid gap-5 lg:grid-cols-[1fr_1fr]"><Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">1. 검사와 케이스</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>프로젝트</Label><select value={form.projectId} onChange={e => update("projectId", e.target.value)} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="">프로젝트 선택</option>{projects.data?.map(project => <option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><Field label="케이스 번호"><Input value={form.caseNumber} onChange={e => update("caseNumber", e.target.value)} /></Field><Field label="환자 별칭"><Input value={form.patientAlias} onChange={e => update("patientAlias", e.target.value)} placeholder="비식별 별칭" /></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="검사 목적"><select value={form.purpose} onChange={e => update("purpose", e.target.value as FormState["purpose"])} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="germline">Germline</option><option value="somatic">Somatic</option></select></Field><Field label="입력 경로"><select value={form.inputType} onChange={e => update("inputType", e.target.value as FormState["inputType"])} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="vcf">VCF</option><option value="fastq">FASTQ paired-end</option></select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Reference build"><select value={form.referenceBuild} onChange={e => update("referenceBuild", e.target.value as FormState["referenceBuild"])} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="GRCh38">GRCh38</option><option value="GRCh37">GRCh37</option></select></Field><Field label="Panel"><Input value={form.panelName} onChange={e => update("panelName", e.target.value)} placeholder="Panel 또는 WES" /></Field></div><Field label="검사 적응증"><Textarea value={form.indication} onChange={e => update("indication", e.target.value)} placeholder="임상 적응증과 핵심 질문" /></Field><Field label="표현형 / 질환 맥락"><Textarea value={form.phenotypeText} onChange={e => update("phenotypeText", e.target.value)} placeholder="HPO 또는 자유 텍스트" /></Field></CardContent></Card>
      <div className="space-y-5"><Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">2. 샘플</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="샘플 코드"><Input value={form.sampleCode} onChange={e => update("sampleCode", e.target.value)} /></Field><Field label="검체 유형"><Input value={form.specimenType} onChange={e => update("specimenType", e.target.value)} /></Field></div>{form.purpose === "somatic" ? <Field label="Tumor content (%)"><Input type="number" min="0" max="100" value={form.tumorContentPercent} onChange={e => update("tumorContentPercent", e.target.value)} /></Field> : null}</CardContent></Card>
        <Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">3. 원본 파일</CardTitle></CardHeader><CardContent>{form.inputType === "vcf" ? <FileInput label="VCF 또는 VCF.GZ" accept=".vcf,.vcf.gz" file={vcf} onChange={setVcf} /> : <div className="grid gap-3"><FileInput label="FASTQ R1" accept=".fastq,.fq,.fastq.gz,.fq.gz" file={r1} onChange={setR1} /><FileInput label="FASTQ R2" accept=".fastq,.fq,.fastq.gz,.fq.gz" file={r2} onChange={setR2} /></div>}</CardContent></Card></div>
    </div>
    <Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">4. 동의와 제출</CardTitle></CardHeader><CardContent className="space-y-4">{[["consentClinicalAnalysis", "임상 분석 동의", "요청한 유전체 분석과 전문가 해석 수행에 동의함"], ["consentSecondaryFindings", "Secondary findings", "별도 정책에 따른 이차 소견 확인에 동의함"], ["consentDataUse", "연구·품질 활용", "비식별 데이터의 연구 및 품질 개선 활용에 동의함"]].map(([key, title, desc]) => <label key={key} className="flex items-start gap-3 rounded-xl border border-border/70 p-4"><Checkbox checked={form[key as keyof FormState] as boolean} onCheckedChange={value => update(key as keyof FormState, Boolean(value) as never)} className="mt-0.5" /><span><span className="block text-sm font-medium">{title}{key === "consentClinicalAnalysis" ? <span className="ml-1 text-destructive">*</span> : null}</span><span className="mt-1 block text-xs text-muted-foreground">{desc}</span></span></label>)}{busy ? <div className="space-y-2"><div className="flex justify-between text-xs"><span>접수 처리 중</span><span className="font-mono">{progress}%</span></div><Progress value={progress} /></div> : null}<div className="flex flex-col-reverse gap-3 border-t border-border/70 pt-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-2 text-[11px] leading-5 text-muted-foreground"><Info className="mt-0.5 size-3.5 shrink-0" />분석 제출 후 원본 파일과 동의 범위는 감사 대상으로 관리됩니다.</div><Button size="lg" disabled={!valid || busy} onClick={handleSubmit}>{busy ? <Loader2 className="mr-2 size-4 animate-spin" /> : <CheckCircle2 className="mr-2 size-4" />}{busy ? "안전하게 접수 중…" : "분석 의뢰 제출"}</Button></div></CardContent></Card>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function FileInput({ label, accept, file, onChange }: { label: string; accept: string; file: File | null; onChange: (file: File | null) => void }) { return <label className={`flex cursor-pointer items-center gap-4 rounded-xl border border-dashed p-4 ${file ? "border-primary/40 bg-primary/[0.035]" : "border-border hover:border-primary/30"}`}><div className="grid size-10 place-items-center rounded-xl bg-muted text-muted-foreground"><FileUp className="size-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium">{file ? file.name : label}</p><p className="mt-1 truncate text-[11px] text-muted-foreground">{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB` : "클릭하여 파일 선택"}</p></div>{file ? <CheckCircle2 className="size-4 text-emerald-600" /> : null}<input type="file" accept={accept} className="hidden" onChange={event => onChange(event.target.files?.[0] || null)} /></label>; }
