import { PageHeader } from "@/components/PageHeader";
import { StatePanel } from "@/components/StatePanel";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useOrganization } from "@/contexts/OrganizationContext";
import { trpc } from "@/lib/trpc";
import type { OrganizationRole } from "@shared/permissions";
import { Copy, MailPlus, UserRoundCog, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const roles: { value: OrganizationRole; label: string; description: string }[] = [
  { value: "administrator", label: "Administrator", description: "조직·멤버·보안 전체 관리" },
  { value: "analyst", label: "Analyst", description: "분석 및 변이 해석" },
  { value: "clinician", label: "Clinician", description: "임상 검토 및 전자서명" },
  { value: "viewer", label: "Viewer", description: "허용된 임상 데이터 열람" },
];

export default function OrganizationPage() {
  const { activeOrganization, activeOrganizationId, hasPermission } = useOrganization(); const utils = trpc.useUtils();
  const enabled = Boolean(activeOrganizationId && hasPermission("member:manage"));
  const members = trpc.organizations.members.useQuery({ organizationId: activeOrganizationId || 0 }, { enabled });
  const invites = trpc.organizations.invites.useQuery({ organizationId: activeOrganizationId || 0 }, { enabled });
  const [email, setEmail] = useState(""); const [role, setRole] = useState<OrganizationRole>("analyst"); const [inviteLink, setInviteLink] = useState("");
  const invite = trpc.organizations.invite.useMutation({ onSuccess: async result => { const link = `${window.location.origin}/invite/${result.token}`; setInviteLink(link); setEmail(""); await utils.organizations.invites.invalidate(); toast.success("7일 유효 초대를 생성했습니다."); }, onError: error => toast.error(error.message) });
  const updateRole = trpc.organizations.updateMemberRole.useMutation({ onSuccess: async () => { await members.refetch(); toast.success("역할을 변경했습니다."); }, onError: error => toast.error(error.message) });
  const revoke = trpc.organizations.revokeInvite.useMutation({ onSuccess: async () => { await invites.refetch(); toast.success("초대를 취소했습니다."); }, onError: error => toast.error(error.message) });
  if (!hasPermission("member:manage")) return <div className="space-y-6"><PageHeader eyebrow="Organization" title="조직 관리" description="현재 조직의 멤버십과 역할 경계를 관리합니다." /><StatePanel type="forbidden" title="멤버 관리 권한이 없습니다" description="조직 관리자에게 member:manage 액션이 포함된 역할을 요청하십시오." /></div>;
  if (members.isError || invites.isError) return <div className="space-y-7"><PageHeader eyebrow="Organization administration" title="조직 및 멤버" description={`${activeOrganization?.name || "현재 조직"}의 멤버십을 불러오지 못했습니다.`} /><StatePanel type="error" title="조직 관리 데이터를 불러오지 못했습니다" description={members.error?.message || invites.error?.message || "잠시 후 다시 시도하십시오."} onRetry={() => { void Promise.all([members.refetch(), invites.refetch()]); }} /></div>;
  return <div className="space-y-7"><PageHeader eyebrow="Organization administration" title="조직 및 멤버" description={`${activeOrganization?.name || "현재 조직"}의 멤버십과 액션 단위 역할을 관리합니다.`} />
    {invite.error || updateRole.error || revoke.error ? <StatePanel compact type="error" title="조직 관리 작업을 완료하지 못했습니다" description={(invite.error || updateRole.error || revoke.error)?.message || "역할과 초대 상태를 확인한 뒤 다시 시도하십시오."} /> : null}
    <section className="grid gap-5 xl:grid-cols-[1.5fr_.8fr]"><Card className="clinical-card shadow-none"><CardHeader><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary/8 text-primary"><UsersRound className="size-4" /></div><div><CardTitle className="font-display text-base">활성 멤버</CardTitle><CardDescription className="mt-1 text-xs">역할 변경은 즉시 서버 권한 경계에 반영됩니다.</CardDescription></div></div></CardHeader><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">사용자</TableHead><TableHead>상태</TableHead><TableHead className="pr-6 text-right">조직 역할</TableHead></TableRow></TableHeader><TableBody>{members.isLoading ? <TableRow><TableCell colSpan={3}><Skeleton className="h-16" /></TableCell></TableRow> : members.data?.map(member => <TableRow key={member.id}><TableCell className="pl-6"><p className="text-xs font-semibold">{member.name || "Unnamed user"}</p><p className="mt-1 text-[10px] text-muted-foreground">{member.email || `User #${member.userId}`}</p></TableCell><TableCell><span className="status-pill bg-emerald-50 text-emerald-700">{member.status}</span></TableCell><TableCell className="pr-6 text-right"><Select value={member.role} onValueChange={value => updateRole.mutate({ organizationId: activeOrganizationId!, memberId: member.id, role: value as OrganizationRole })}><SelectTrigger className="ml-auto w-40"><SelectValue /></SelectTrigger><SelectContent>{roles.map(item => <SelectItem key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
      <Card className="clinical-card shadow-none"><CardHeader><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary/8 text-primary"><MailPlus className="size-4" /></div><div><CardTitle className="font-display text-base">멤버 초대</CardTitle><CardDescription className="mt-1 text-xs">초대 링크는 7일 후 만료됩니다.</CardDescription></div></div></CardHeader><CardContent><form className="space-y-4" onSubmit={event => { event.preventDefault(); invite.mutate({ organizationId: activeOrganizationId!, email, role }); }}><div className="space-y-2"><Label htmlFor="invite-email">이메일</Label><Input id="invite-email" type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="clinician@hospital.org" required /></div><div className="space-y-2"><Label>역할</Label><Select value={role} onValueChange={value => setRole(value as OrganizationRole)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{roles.map(item => <SelectItem key={item.value} value={item.value}><div><p>{item.label}</p><p className="text-[10px] text-muted-foreground">{item.description}</p></div></SelectItem>)}</SelectContent></Select></div><Button className="w-full" disabled={invite.isPending}><MailPlus className="mr-2 size-4" />초대 생성</Button></form>{inviteLink ? <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><p className="text-[10px] font-semibold text-emerald-800">초대 링크</p><div className="mt-2 flex gap-2"><Input readOnly value={inviteLink} className="h-8 bg-white text-[10px]" /><Button size="icon" variant="outline" onClick={() => { navigator.clipboard.writeText(inviteLink); toast.success("링크를 복사했습니다."); }}><Copy className="size-3" /></Button></div></div> : null}</CardContent></Card></section>
    <Card className="clinical-card shadow-none"><CardHeader><div className="flex items-center gap-3"><UserRoundCog className="size-4 text-primary" /><div><CardTitle className="font-display text-base">초대 이력</CardTitle><CardDescription className="mt-1 text-xs">대기 중인 초대는 즉시 취소할 수 있습니다.</CardDescription></div></div></CardHeader><CardContent className="px-0"><Table><TableHeader><TableRow><TableHead className="pl-6">이메일</TableHead><TableHead>역할</TableHead><TableHead>만료</TableHead><TableHead className="pr-6 text-right">상태</TableHead></TableRow></TableHeader><TableBody>{invites.data?.length ? invites.data.map(item => { const state = item.acceptedAt ? "accepted" : item.revokedAt ? "revoked" : new Date(item.expiresAt).getTime() < Date.now() ? "expired" : "pending"; return <TableRow key={item.id}><TableCell className="pl-6 text-xs font-medium">{item.email}</TableCell><TableCell className="text-xs capitalize">{item.role}</TableCell><TableCell className="text-[10px] text-muted-foreground">{new Date(item.expiresAt).toLocaleString()}</TableCell><TableCell className="pr-6 text-right"><div className="flex items-center justify-end gap-2"><span className="status-pill bg-muted text-muted-foreground">{state}</span>{state === "pending" ? <Button size="icon" variant="ghost" aria-label="초대 취소" onClick={() => revoke.mutate({ organizationId: activeOrganizationId!, inviteId: item.id })}><X className="size-3.5" /></Button> : null}</div></TableCell></TableRow>; }) : <TableRow><TableCell colSpan={4} className="py-10 text-center text-xs text-muted-foreground">초대 이력이 없습니다.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
  </div>;
}
