import { ClinicalStatus } from "@/components/ClinicalStatus";
import { PageHeader } from "@/components/PageHeader";
import { StatePanel } from "@/components/StatePanel";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { useOrganization } from "@/contexts/OrganizationContext";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, FileCheck2, Hash, LockKeyhole, PenLine, Printer, Save, ShieldCheck, Undo2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation, useParams } from "wouter";

type ReportContent = { summary: string; indication: string; findings: string; interpretation: string; methodology: string; limitations: string; recommendations: string };
const emptyContent: ReportContent = { summary: "", indication: "", findings: "", interpretation: "", methodology: "", limitations: "", recommendations: "" };

export default function ReportEditorPage() {
  const params = useParams<{ id: string }>(); const reportId = Number(params.id);
  const { activeOrganizationId, hasPermission } = useOrganization(); const [, navigate] = useLocation();
  const query = trpc.reports.get.useQuery({ organizationId: activeOrganizationId || 0, reportId }, { enabled: Boolean(activeOrganizationId && reportId && hasPermission("report:read")) });
  const [title, setTitle] = useState(""); const [content, setContent] = useState<ReportContent>(emptyContent); const [attestation, setAttestation] = useState(false);
  const [amendReason, setAmendReason] = useState(""); const [amendOpen, setAmendOpen] = useState(false);
  useEffect(() => { if (query.data) { setTitle(query.data.report.title); setContent({ ...emptyContent, ...(query.data.report.content as Partial<ReportContent>) }); } }, [query.data]);
  const update = trpc.reports.update.useMutation({ onSuccess: async () => { await query.refetch(); toast.success("Report draft saved."); }, onError: error => toast.error(error.message) });
  const review = trpc.reports.submitReview.useMutation({ onSuccess: async () => { await query.refetch(); toast.success("Transitioned to clinician review status."); }, onError: error => toast.error(error.message) });
  const returnToDraft = trpc.reports.returnToDraft.useMutation({ onSuccess: async () => { await query.refetch(); toast.success("Report returned to draft."); }, onError: error => toast.error(error.message) });
  const sign = trpc.reports.sign.useMutation({ onSuccess: async result => { await query.refetch(); toast.success(`Electronic signature complete · ${result.snapshotHash.slice(0, 12)}…`); }, onError: error => toast.error(error.message) });
  const amend = trpc.reports.amend.useMutation({
    onSuccess: result => {
      setAmendOpen(false);
      setAmendReason("");
      toast.success("Amendment draft created.");
      navigate(`/reports/${result.id}`);
    },
    onError: error => toast.error(error.message),
  });
  if (!hasPermission("report:read")) return <div className="space-y-7"><PageHeader eyebrow="Clinical reporting" title="Reports" description="View clinical reports within the organization boundary." /><StatePanel type="forbidden" title="You do not have permission to view reports" description="Ask your organization administrator for a role that includes the report:read action." action={<Button variant="outline" onClick={() => navigate("/")}>Dashboard</Button>} /></div>;
  if (query.isLoading) return <div className="space-y-5"><Skeleton className="h-20" /><Skeleton className="h-[700px]" /></div>;
  if (query.isError) return <div className="space-y-7"><PageHeader eyebrow="Clinical reporting" title="Report error" description="Unable to verify the requested report and organization access boundary." actions={<Button variant="outline" onClick={() => navigate("/reports")}><ArrowLeft className="mr-2 size-4" />Back</Button>} /><StatePanel type="error" title="Failed to load report" description={query.error.message} onRetry={() => { void query.refetch(); }} /></div>;
  if (!query.data) return <div className="space-y-7"><PageHeader eyebrow="Clinical reporting" title="Report not found" description="Please verify the requested report identifier." /><StatePanel type="empty" title="Report not found" description="Reports that have been deleted or do not belong to the current organization are not shown." action={<Button variant="outline" onClick={() => navigate("/reports")}><ArrowLeft className="mr-2 size-4" />Reports</Button>} /></div>;
  const { report, clinicalCase, signerName, signerEmail } = query.data; const editable = report.status === "draft" && hasPermission("report:draft");
  const fields: { key: keyof ReportContent; label: string; rows: number }[] = [{ key: "summary", label: "Result summary", rows: 4 }, { key: "indication", label: "Clinical indication", rows: 3 }, { key: "findings", label: "Key findings", rows: 7 }, { key: "interpretation", label: "Clinical interpretation", rows: 9 }, { key: "methodology", label: "Methodology", rows: 5 }, { key: "limitations", label: "Limitations", rows: 5 }, { key: "recommendations", label: "Recommendations", rows: 4 }];
  const actionError = update.error || review.error || returnToDraft.error || sign.error || amend.error;
  return <div className="space-y-6"><div className="no-print"><PageHeader eyebrow={`Report v${report.version}`} title={report.title} description={`${clinicalCase.caseNumber} · ${clinicalCase.patientAlias} · ${clinicalCase.purpose}`} badge={report.status} actions={<><Button variant="outline" onClick={() => navigate("/reports")}><ArrowLeft className="mr-2 size-4" />Back</Button><Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 size-4" />Print / PDF</Button></>} /></div>
    {report.status === "signed" || report.status === "amended" ? <Alert className="no-print border-emerald-200 bg-emerald-50/65 text-emerald-950"><LockKeyhole className="size-4 text-emerald-700" /><AlertTitle>Immutable clinical snapshot</AlertTitle><AlertDescription className="text-emerald-800/80">This version has been electronically signed and cannot be modified. You can verify the integrity of the displayed content using the SHA-256 hash.</AlertDescription></Alert> : null}
    {actionError ? <div className="no-print"><StatePanel compact type="error" title="Failed to complete report action" description={actionError.message || "Check the status transition and role permissions, then try again."} /></div> : null}
    <article className="report-sheet mx-auto max-w-5xl bg-white p-8 text-slate-900 sm:p-12"><header className="border-b-2 border-slate-900 pb-7"><div className="flex items-start justify-between gap-8"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-teal-700">Genolyx Variant Interpreter</p>{editable ? <Input value={title} onChange={event => setTitle(event.target.value)} className="mt-3 h-auto border-0 p-0 font-display text-2xl font-semibold shadow-none focus-visible:ring-0" /> : <h1 className="mt-3 font-display text-2xl font-semibold">{title}</h1>}<p className="mt-3 font-mono text-xs text-slate-500">{clinicalCase.caseNumber} · Version {report.version}</p></div><div className="text-right"><ClinicalStatus status={report.status} /><p className="mt-3 text-[10px] text-slate-500">Generated {new Date(report.createdAt).toLocaleDateString()}</p></div></div><div className="mt-7 grid gap-4 rounded-xl bg-slate-50 p-5 text-xs sm:grid-cols-4"><div><span className="block text-[9px] uppercase text-slate-500">Patient alias</span><strong className="mt-1 block">{clinicalCase.patientAlias}</strong></div><div><span className="block text-[9px] uppercase text-slate-500">Purpose</span><strong className="mt-1 block capitalize">{clinicalCase.purpose}</strong></div><div><span className="block text-[9px] uppercase text-slate-500">Reference</span><strong className="mt-1 block">{clinicalCase.referenceBuild}</strong></div><div><span className="block text-[9px] uppercase text-slate-500">Panel</span><strong className="mt-1 block">{clinicalCase.panelName || "—"}</strong></div></div></header>
      <div className="mt-8 space-y-8">{fields.map(field => <section key={field.key}><h2 className="border-b border-slate-200 pb-2 text-xs font-bold uppercase tracking-[.16em] text-slate-700">{field.label}</h2>{editable ? <Textarea value={content[field.key]} onChange={event => setContent(current => ({ ...current, [field.key]: event.target.value }))} rows={field.rows} className="mt-3 resize-y border-slate-200 bg-slate-50/50 text-sm leading-7" /> : <div className="mt-3 whitespace-pre-wrap text-sm leading-7">{content[field.key] || "—"}</div>}</section>)}</div>
      {report.snapshotHash ? <footer className="mt-10 border-t-2 border-slate-900 pt-6"><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-[9px] uppercase tracking-wider text-slate-500">Electronic signature</p><p className="mt-2 text-sm font-semibold">{signerName || signerEmail || "Verified clinician"}</p><p className="mt-1 text-[10px] text-slate-500">{report.signedAt ? new Date(report.signedAt).toLocaleString() : ""}</p></div><div><p className="flex items-center gap-1 text-[9px] uppercase tracking-wider text-slate-500"><Hash className="size-3" />SHA-256 snapshot digest</p><p className="mt-2 break-all font-mono text-[9px] leading-4">{report.snapshotHash}</p></div></div></footer> : null}
    </article>
    <div className="no-print mx-auto flex max-w-5xl flex-col gap-3 rounded-2xl border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary/8 text-primary">{report.status === "draft" ? <PenLine className="size-4" /> : report.status === "in_review" ? <FileCheck2 className="size-4" /> : <ShieldCheck className="size-4" />}</div><div><p className="text-xs font-semibold">{report.status === "draft" ? "Editable draft" : report.status === "in_review" ? "Awaiting electronic signature" : "Signed immutable version"}</p><p className="mt-1 text-[10px] text-muted-foreground">The server re-validates allowed status transitions and roles.</p></div></div><div className="flex flex-wrap gap-2">
      {editable ? <><Button variant="outline" disabled={update.isPending} onClick={() => update.mutate({ organizationId: activeOrganizationId!, reportId, title, content })}><Save className="mr-2 size-4" />Save</Button>{hasPermission("report:review") ? <Button disabled={review.isPending} onClick={() => review.mutate({ organizationId: activeOrganizationId!, reportId })}><CheckCircle2 className="mr-2 size-4" />In Review</Button> : null}</> : null}
      {report.status === "in_review" && hasPermission("report:review") ? <Button variant="outline" disabled={returnToDraft.isPending} onClick={() => returnToDraft.mutate({ organizationId: activeOrganizationId!, reportId })}><Undo2 className="mr-2 size-4" />Return to draft</Button> : null}
      {report.status === "in_review" && hasPermission("report:sign") ? <Dialog><DialogTrigger asChild><Button><ShieldCheck className="mr-2 size-4" />Sign</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Sign clinical report</DialogTitle><DialogDescription>After signing, this version cannot be modified. Please verify that you have reviewed all content and evidence.</DialogDescription></DialogHeader><label className="flex items-start gap-3 rounded-xl border p-4"><Checkbox checked={attestation} onCheckedChange={value => setAttestation(Boolean(value))} className="mt-0.5" /><span className="text-xs leading-5">I have reviewed this report and electronically sign the current version, including the clinical interpretation and limitations shown.</span></label><DialogFooter><Button disabled={!attestation || sign.isPending} onClick={() => sign.mutate({ organizationId: activeOrganizationId!, reportId, confirmReportId: reportId, attestation: true })}>Create immutable snapshot and sign</Button></DialogFooter></DialogContent></Dialog> : null}
      {report.status === "signed" && hasPermission("report:draft") ? <Dialog open={amendOpen} onOpenChange={setAmendOpen}><DialogTrigger asChild><Button variant="outline"><PenLine className="mr-2 size-4" />Amend</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Amend signed report</DialogTitle><DialogDescription>Creates a new draft version linked to this signed snapshot. The original remains immutable.</DialogDescription></DialogHeader><div className="space-y-2"><Label htmlFor="amend-reason">Amendment reason</Label><Textarea id="amend-reason" value={amendReason} onChange={event => setAmendReason(event.target.value)} rows={4} placeholder="Describe why this report needs amendment (minimum 10 characters)." /></div><DialogFooter><Button disabled={amendReason.trim().length < 10 || amend.isPending} onClick={() => amend.mutate({ organizationId: activeOrganizationId!, reportId, reason: amendReason.trim() })}>Create amendment draft</Button></DialogFooter></DialogContent></Dialog> : null}
    </div></div>
  </div>;
}
