import { ClinicalStatus } from "@/components/ClinicalStatus";
import { PageHeader } from "@/components/PageHeader";
import { StatePanel } from "@/components/StatePanel";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { useOrganization } from "@/contexts/OrganizationContext";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, FileCheck2, Hash, LockKeyhole, PenLine, Printer, Save, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation, useParams } from "wouter";

type ReportContent = { summary: string; indication: string; findings: string; interpretation: string; methodology: string; limitations: string; recommendations: string };
const emptyContent: ReportContent = { summary: "", indication: "", findings: "", interpretation: "", methodology: "", limitations: "", recommendations: "" };

export default function ReportEditorPage() {
  const params = useParams<{ id: string }>(); const reportId = Number(params.id);
  const { activeOrganizationId, hasPermission } = useOrganization(); const [, navigate] = useLocation();
  const query = trpc.reports.get.useQuery({ organizationId: activeOrganizationId || 0, reportId }, { enabled: Boolean(activeOrganizationId && reportId && hasPermission("report:read")) });
  const [title, setTitle] = useState(""); const [content, setContent] = useState<ReportContent>(emptyContent); const [attestation, setAttestation] = useState(false);
  useEffect(() => { if (query.data) { setTitle(query.data.report.title); setContent({ ...emptyContent, ...(query.data.report.content as Partial<ReportContent>) }); } }, [query.data]);
  const update = trpc.reports.update.useMutation({ onSuccess: async () => { await query.refetch(); toast.success("보고서 초안을 저장했습니다."); }, onError: error => toast.error(error.message) });
  const review = trpc.reports.submitReview.useMutation({ onSuccess: async () => { await query.refetch(); toast.success("전문의 검토 상태로 전환했습니다."); }, onError: error => toast.error(error.message) });
  const sign = trpc.reports.sign.useMutation({ onSuccess: async result => { await query.refetch(); toast.success(`전자서명 완료 · ${result.snapshotHash.slice(0, 12)}…`); }, onError: error => toast.error(error.message) });
  if (!hasPermission("report:read")) return <div className="space-y-7"><PageHeader eyebrow="Clinical reporting" title="보고서" description="조직 범위의 임상 보고서를 조회합니다." /><StatePanel type="forbidden" title="보고서 조회 권한이 없습니다" description="조직 관리자에게 report:read 액션이 포함된 역할을 요청하십시오." action={<Button variant="outline" onClick={() => navigate("/")}>대시보드</Button>} /></div>;
  if (query.isLoading) return <div className="space-y-5"><Skeleton className="h-20" /><Skeleton className="h-[700px]" /></div>;
  if (query.isError) return <div className="space-y-7"><PageHeader eyebrow="Clinical reporting" title="보고서 조회 오류" description="요청한 보고서와 조직 접근 경계를 확인할 수 없습니다." actions={<Button variant="outline" onClick={() => navigate("/reports")}><ArrowLeft className="mr-2 size-4" />목록</Button>} /><StatePanel type="error" title="보고서를 불러오지 못했습니다" description={query.error.message} onRetry={() => { void query.refetch(); }} /></div>;
  if (!query.data) return <div className="space-y-7"><PageHeader eyebrow="Clinical reporting" title="보고서 없음" description="요청한 보고서 식별자를 확인하십시오." /><StatePanel type="empty" title="보고서를 찾을 수 없습니다" description="삭제되었거나 현재 조직에 속하지 않은 보고서는 노출되지 않습니다." action={<Button variant="outline" onClick={() => navigate("/reports")}><ArrowLeft className="mr-2 size-4" />보고서 목록</Button>} /></div>;
  const { report, clinicalCase, signerName, signerEmail } = query.data; const editable = report.status === "draft" && hasPermission("report:draft");
  const fields: { key: keyof ReportContent; label: string; rows: number }[] = [{ key: "summary", label: "Result summary", rows: 4 }, { key: "indication", label: "Clinical indication", rows: 3 }, { key: "findings", label: "Key findings", rows: 7 }, { key: "interpretation", label: "Clinical interpretation", rows: 9 }, { key: "methodology", label: "Methodology", rows: 5 }, { key: "limitations", label: "Limitations", rows: 5 }, { key: "recommendations", label: "Recommendations", rows: 4 }];
  return <div className="space-y-6"><div className="no-print"><PageHeader eyebrow={`Report v${report.version}`} title={report.title} description={`${clinicalCase.caseNumber} · ${clinicalCase.patientAlias} · ${clinicalCase.purpose}`} badge={report.status} actions={<><Button variant="outline" onClick={() => navigate("/reports")}><ArrowLeft className="mr-2 size-4" />목록</Button><Button variant="outline" onClick={() => window.print()}><Printer className="mr-2 size-4" />인쇄/PDF</Button></>} /></div>
    {report.status === "signed" || report.status === "amended" ? <Alert className="no-print border-emerald-200 bg-emerald-50/65 text-emerald-950"><LockKeyhole className="size-4 text-emerald-700" /><AlertTitle>불변 임상 스냅샷</AlertTitle><AlertDescription className="text-emerald-800/80">이 버전은 전자서명되었으며 수정할 수 없습니다. SHA-256 해시로 표시 내용의 무결성을 검증할 수 있습니다.</AlertDescription></Alert> : null}
    {update.error || review.error || sign.error ? <div className="no-print"><StatePanel compact type="error" title="보고서 작업을 완료하지 못했습니다" description={(update.error || review.error || sign.error)?.message || "상태 전이와 역할 권한을 확인한 뒤 다시 시도하십시오."} /></div> : null}
    <article className="report-sheet mx-auto max-w-5xl bg-white p-8 text-slate-900 sm:p-12"><header className="border-b-2 border-slate-900 pb-7"><div className="flex items-start justify-between gap-8"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-teal-700">Genolyx Variant Interpreter</p>{editable ? <Input value={title} onChange={event => setTitle(event.target.value)} className="mt-3 h-auto border-0 p-0 font-display text-2xl font-semibold shadow-none focus-visible:ring-0" /> : <h1 className="mt-3 font-display text-2xl font-semibold">{title}</h1>}<p className="mt-3 font-mono text-xs text-slate-500">{clinicalCase.caseNumber} · Version {report.version}</p></div><div className="text-right"><ClinicalStatus status={report.status} /><p className="mt-3 text-[10px] text-slate-500">Generated {new Date(report.createdAt).toLocaleDateString()}</p></div></div><div className="mt-7 grid gap-4 rounded-xl bg-slate-50 p-5 text-xs sm:grid-cols-4"><div><span className="block text-[9px] uppercase text-slate-500">Patient alias</span><strong className="mt-1 block">{clinicalCase.patientAlias}</strong></div><div><span className="block text-[9px] uppercase text-slate-500">Purpose</span><strong className="mt-1 block capitalize">{clinicalCase.purpose}</strong></div><div><span className="block text-[9px] uppercase text-slate-500">Reference</span><strong className="mt-1 block">{clinicalCase.referenceBuild}</strong></div><div><span className="block text-[9px] uppercase text-slate-500">Panel</span><strong className="mt-1 block">{clinicalCase.panelName || "—"}</strong></div></div></header>
      <div className="mt-8 space-y-8">{fields.map(field => <section key={field.key}><h2 className="border-b border-slate-200 pb-2 text-xs font-bold uppercase tracking-[.16em] text-slate-700">{field.label}</h2>{editable ? <Textarea value={content[field.key]} onChange={event => setContent(current => ({ ...current, [field.key]: event.target.value }))} rows={field.rows} className="mt-3 resize-y border-slate-200 bg-slate-50/50 text-sm leading-7" /> : <div className="mt-3 whitespace-pre-wrap text-sm leading-7">{content[field.key] || "—"}</div>}</section>)}</div>
      {report.snapshotHash ? <footer className="mt-10 border-t-2 border-slate-900 pt-6"><div className="grid gap-5 sm:grid-cols-2"><div><p className="text-[9px] uppercase tracking-wider text-slate-500">Electronic signature</p><p className="mt-2 text-sm font-semibold">{signerName || signerEmail || "Verified clinician"}</p><p className="mt-1 text-[10px] text-slate-500">{report.signedAt ? new Date(report.signedAt).toLocaleString() : ""}</p></div><div><p className="flex items-center gap-1 text-[9px] uppercase tracking-wider text-slate-500"><Hash className="size-3" />SHA-256 snapshot digest</p><p className="mt-2 break-all font-mono text-[9px] leading-4">{report.snapshotHash}</p></div></div></footer> : null}
    </article>
    <div className="no-print mx-auto flex max-w-5xl flex-col gap-3 rounded-2xl border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-primary/8 text-primary">{report.status === "draft" ? <PenLine className="size-4" /> : report.status === "in_review" ? <FileCheck2 className="size-4" /> : <ShieldCheck className="size-4" />}</div><div><p className="text-xs font-semibold">{report.status === "draft" ? "편집 가능한 초안" : report.status === "in_review" ? "전자서명 대기" : "서명된 불변 버전"}</p><p className="mt-1 text-[10px] text-muted-foreground">서버가 허용된 상태 전이와 역할을 다시 검증합니다.</p></div></div><div className="flex flex-wrap gap-2">{editable ? <><Button variant="outline" disabled={update.isPending} onClick={() => update.mutate({ organizationId: activeOrganizationId!, reportId, title, content })}><Save className="mr-2 size-4" />저장</Button>{hasPermission("report:review") ? <Button disabled={review.isPending} onClick={() => review.mutate({ organizationId: activeOrganizationId!, reportId })}><CheckCircle2 className="mr-2 size-4" />In Review</Button> : null}</> : null}{report.status === "in_review" && hasPermission("report:sign") ? <Dialog><DialogTrigger asChild><Button><ShieldCheck className="mr-2 size-4" />전자서명</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>임상 보고서 전자서명</DialogTitle><DialogDescription>서명 후 이 버전은 수정할 수 없습니다. 내용과 근거를 모두 검토했는지 확인하십시오.</DialogDescription></DialogHeader><label className="flex items-start gap-3 rounded-xl border p-4"><Checkbox checked={attestation} onCheckedChange={value => setAttestation(Boolean(value))} className="mt-0.5" /><span className="text-xs leading-5">본인은 이 보고서를 검토했으며, 표시된 임상 해석과 제한점을 포함한 현재 버전에 전자서명합니다.</span></label><DialogFooter><Button disabled={!attestation || sign.isPending} onClick={() => sign.mutate({ organizationId: activeOrganizationId!, reportId, confirmReportId: reportId, attestation: true })}>불변 스냅샷 생성 및 서명</Button></DialogFooter></DialogContent></Dialog> : null}</div></div>
  </div>;
}
