import { PageHeader } from "@/components/PageHeader";
import { StatePanel } from "@/components/StatePanel";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useOrganization } from "@/contexts/OrganizationContext";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Database, Fingerprint, FolderLock, HardDrive, KeyRound, LockKeyhole, Network, ShieldCheck } from "lucide-react";

export default function SecurityConsolePage() {
  const { activeOrganizationId, hasPermission } = useOrganization(); const query = trpc.organizations.securityContext.useQuery({ organizationId: activeOrganizationId || 0 }, { enabled: Boolean(activeOrganizationId && hasPermission("security:view")) });
  if (query.isLoading) return <div className="space-y-5"><Skeleton className="h-24" /><Skeleton className="h-96" /></div>;
  if (query.isError) return <div className="space-y-7"><PageHeader eyebrow="Security transparency" title="Security Console" description="Failed to load the security context for the current organization." /><StatePanel type="error" title="Failed to load security context" description={query.error.message} onRetry={() => { void query.refetch(); }} /></div>;
  if (!query.data) return <div className="space-y-7"><PageHeader eyebrow="Security transparency" title="Security Console" description="Describes the security context and organization isolation controls for the current principal." /><StatePanel type="forbidden" title="You do not have permission to view the security context" description="Ask your organization administrator for a role that includes the security:view action. Organization data outside your permissions remains hidden." /></div>;
  const data = query.data; const icons = [Database, Network, KeyRound, HardDrive, Fingerprint];
  return <div className="space-y-7"><PageHeader eyebrow="Security transparency" title="Security Console" description="Describes the exact organization and project scope accessible to the current principal, and the isolation controls in effect." badge="enforced" />
    <section className="overflow-hidden rounded-2xl bg-slate-950 p-6 text-white shadow-xl shadow-slate-950/10 sm:p-8"><div className="grid items-center gap-8 lg:grid-cols-[1fr_1.15fr]"><div><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-teal-400/10 text-teal-300 ring-1 ring-teal-300/20"><ShieldCheck className="size-5" /></div><div><p className="text-[10px] uppercase tracking-[.18em] text-slate-400">Verified tenant boundary</p><h2 className="mt-1 font-display text-xl font-semibold">{data.organization.name}</h2></div></div><dl className="mt-7 grid grid-cols-2 gap-4 text-xs"><div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><dt className="text-[9px] uppercase text-slate-500">Tenant ID</dt><dd className="mt-2 font-mono">ORG-{String(data.organization.id).padStart(6, "0")}</dd></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><dt className="text-[9px] uppercase text-slate-500">Data region</dt><dd className="mt-2">{data.organization.dataRegion}</dd></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><dt className="text-[9px] uppercase text-slate-500">Isolation mode</dt><dd className="mt-2 text-teal-300">{data.organization.isolationMode}</dd></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-4"><dt className="text-[9px] uppercase text-slate-500">Effective role</dt><dd className="mt-2 capitalize">{data.role}</dd></div></dl></div><div className="relative rounded-2xl border border-white/10 bg-white/[.025] p-6"><div className="absolute inset-y-10 left-1/2 w-px bg-gradient-to-b from-transparent via-teal-400/50 to-transparent" /><div className="relative z-10 grid grid-cols-[1fr_auto_1fr] items-center gap-4"><div className="rounded-xl border border-teal-300/20 bg-teal-400/5 p-4 text-center"><FolderLock className="mx-auto size-5 text-teal-300" /><p className="mt-2 text-[10px] font-semibold">Current organization</p><p className="mt-1 font-mono text-[8px] text-slate-500">{data.organization.slug}</p></div><div className="grid size-10 place-items-center rounded-full bg-teal-300 text-slate-950 ring-8 ring-teal-300/10"><LockKeyhole className="size-4" /></div><div className="rounded-xl border border-rose-300/10 bg-rose-400/[.03] p-4 text-center opacity-60"><FolderLock className="mx-auto size-5 text-rose-300" /><p className="mt-2 text-[10px] font-semibold">Other organizations</p><p className="mt-1 font-mono text-[8px] text-slate-500">Access denied</p></div></div><p className="mt-5 text-center text-[9px] leading-5 text-slate-500">All clinical queries execute within the organizationId scope of the authenticated membership.</p></div></div></section>
    <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">Isolation control status</CardTitle><CardDescription className="text-xs">Core controls enforced at the application and data storage boundary.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{data.controls.map((control, index) => { const Icon = icons[index] || ShieldCheck; return <div key={control.key} className="flex gap-3 rounded-xl border border-border/70 p-4"><div className="grid size-8 shrink-0 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Icon className="size-4" /></div><div><p className="text-xs font-semibold leading-5">{control.label}</p><p className="mt-1 flex items-center gap-1 text-[9px] uppercase tracking-wider text-emerald-700"><CheckCircle2 className="size-3" />{control.state}</p></div></div>; })}</CardContent></Card><Card className="clinical-card shadow-none"><CardHeader><CardTitle className="font-display text-base">Accessible scope</CardTitle><CardDescription className="text-xs">Projects the current principal can access.</CardDescription></CardHeader><CardContent className="space-y-3">{data.accessibleProjects.length ? data.accessibleProjects.map(project => <div key={project.id} className="rounded-xl border border-border/70 p-4"><div className="flex items-center gap-2"><div className="size-2 rounded-full bg-emerald-500" /><p className="text-xs font-semibold">{project.name}</p></div><p className="mt-2 font-mono text-[9px] text-muted-foreground">{project.code} · PROJECT-{project.id}</p></div>) : <p className="py-8 text-center text-xs text-muted-foreground">No active projects.</p>}<div className="rounded-xl bg-muted/60 p-4"><p className="text-[9px] font-semibold uppercase tracking-wider text-muted-foreground">Effective actions</p><div className="mt-3 flex flex-wrap gap-1.5">{data.permissions.map(permission => <span key={permission} className="rounded-md border bg-card px-2 py-1 font-mono text-[8px]">{permission}</span>)}</div></div></CardContent></Card></section>
  </div>;
}
